services:
    - type: web
      name: tiktok-age-checker-api
      env: docker
      branch: main
      dockerfilePath: ./Dockerfile
      envVars:
        - key: MS_TOKEN
          sync: false
        - key: PORT
          value: 8000
